; ============================================================
;  Smart Water Tank - PlatformIO project
;  Nap chuong trinh chinh    : pio run -e main -t upload
;  Nap chuong trinh kiem thu : pio run -e test_level -t upload
; ============================================================
[platformio]
default_envs = main

[env]
platform  = espressif32@^6.5.0
board     = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.5
build_flags = -DCORE_DEBUG_LEVEL=0

[env:main]
build_src_filter = +<*> -<tests/>

[env:test_level]
build_src_filter = -<*> +<tests/step2_level.cpp>

[env:test_relay]
build_src_filter = -<*> +<tests/step3_relay.cpp>

[env:test_flow]
build_src_filter = -<*> +<tests/step5_flow.cpp>

[env:test_current]
build_src_filter = -<*> +<tests/step6_current.cpp>

[env:test_floats]
build_src_filter = -<*> +<tests/step7_floats.cpp>

[env:test_calib]
build_src_filter = -<*> +<tests/step8_calib.cpp>

[env:test_flownoise]
build_src_filter = -<*> +<tests/step9_flownoise.cpp>

[env:test_relaytruth]
build_src_filter = -<*> +<tests/step10_relaytruth.cpp>

[env:test_flowmap]
build_src_filter = -<*> +<tests/step11_flowmap.cpp>

[env:test_pumpecho]
build_src_filter = -<*> +<tests/step12_pumpecho.cpp>

[env:test_wifiscan]
build_src_filter = -<*> +<tests/step13_wifiscan.cpp>
